name: es-tutorial
channels:
    - conda-forge
    - defaults
dependencies:

    - python
    - pip

    # notebooks
    - jupyter
    - jupyterlab

    # utilities
    - ipython
    - numpy
    - pandas
    - networkx
    - matplotlib

    # optimisation
    - pyomo
    - glpk

